
### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "CS203"
keywords:    "QCC, CS203"
description: "CS203"
source_link: "https://qcc-cs203.github.com/qcc-cs203.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
#google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

course:
  name: 'CS203 - Algorithmic Problem Solving II'
  short: 'CS203'
  semester: '2015S'
  section: 'D124' 
  instructor: 'KWANG KIM'
  dept:  'Mathematics and Computer Science'
  depturl: http://www.qcc.cuny.edu/mathCS/
  contactchair: mailto:kkim@qcc.cuny.edu
  collegeshort: QCC
  collegeurl: http://www.qcc.cuny.edu

  
